"""Gateway Group - Complete Database Seed (ALL Excel data: 128 HK items, 10 locations, 10 vendors)"""
from app.database import SessionLocal, engine
from app import models
from datetime import date

models.Base.metadata.drop_all(bind=engine)
models.Base.metadata.create_all(bind=engine)
db = SessionLocal()

try:
    print("Seeding locations...")
    locations = [
        models.LocationModel(code="CH-1B",    name="Corporate HQ - 1B",  city="Ahmedabad",   type="Office", contact_person="Site Manager", phone="079-26300001", status="Active", area_sqft=1500, headcount=25, num_washrooms=2, num_urinals=2, num_wcs=4, num_wash_basins=4, num_pantries=1, num_meeting_rooms=2, num_ac_units=4,  num_fans=6),
        models.LocationModel(code="CH-2B",    name="Corporate HQ - 2B",  city="Ahmedabad",   type="Office", contact_person="Site Manager", phone="079-26300002", status="Active", area_sqft=1500, headcount=30, num_washrooms=2, num_urinals=2, num_wcs=4, num_wash_basins=4, num_pantries=1, num_meeting_rooms=2, num_ac_units=4,  num_fans=6),
        models.LocationModel(code="CH-3B1",   name="Corporate HQ - 3B1", city="Ahmedabad",   type="Office", contact_person="Site Manager", phone="079-26300003", status="Active", area_sqft=1500, headcount=28, num_washrooms=2, num_urinals=2, num_wcs=4, num_wash_basins=4, num_pantries=1, num_meeting_rooms=2, num_ac_units=4,  num_fans=6),
        models.LocationModel(code="CH-4A1",   name="Corporate HQ - 4A1", city="Ahmedabad",   type="Office", contact_person="Site Manager", phone="079-26300004", status="Active", area_sqft=1500, headcount=22, num_washrooms=2, num_urinals=2, num_wcs=4, num_wash_basins=4, num_pantries=1, num_meeting_rooms=1, num_ac_units=4,  num_fans=6),
        models.LocationModel(code="CH-5A1",   name="Corporate HQ - 5A1", city="Ahmedabad",   type="Office", contact_person="Site Manager", phone="079-26300005", status="Active", area_sqft=1500, headcount=20, num_washrooms=2, num_urinals=2, num_wcs=4, num_wash_basins=4, num_pantries=1, num_meeting_rooms=1, num_ac_units=4,  num_fans=6),
        models.LocationModel(code="MS",       name="Gandhinagar Site",   city="Gandhinagar", type="Office", contact_person="Site Manager", phone="079-26300006", status="Active", area_sqft=3000, headcount=50, num_washrooms=4, num_urinals=4, num_wcs=8, num_wash_basins=8, num_pantries=2, num_meeting_rooms=3, num_ac_units=8,  num_fans=12),
        models.LocationModel(code="BRD",      name="Baroda Office",      city="Baroda",      type="Branch", contact_person="Site Manager", phone="0265-2600001", status="Active", area_sqft=1200, headcount=15, num_washrooms=2, num_urinals=1, num_wcs=3, num_wash_basins=3, num_pantries=1, num_meeting_rooms=1, num_ac_units=3,  num_fans=4),
        models.LocationModel(code="RJKT",     name="Rajkot Office",      city="Rajkot",      type="Branch", contact_person="Site Manager", phone="0281-2600001", status="Active", area_sqft=1000, headcount=12, num_washrooms=1, num_urinals=1, num_wcs=2, num_wash_basins=2, num_pantries=1, num_meeting_rooms=1, num_ac_units=2,  num_fans=3),
        models.LocationModel(code="PUN",      name="Pune Office",        city="Pune",        type="Branch", contact_person="Site Manager", phone="020-26000001", status="Active", area_sqft=1200, headcount=18, num_washrooms=2, num_urinals=2, num_wcs=3, num_wash_basins=3, num_pantries=1, num_meeting_rooms=1, num_ac_units=3,  num_fans=4),
        models.LocationModel(code="STORE-CH", name="Central Store - CH", city="Ahmedabad",   type="Store",  contact_person="Store Manager", phone="079-26300010", status="Active", area_sqft=500,  headcount=3,  num_washrooms=1, num_urinals=1, num_wcs=1, num_wash_basins=1, num_pantries=0, num_meeting_rooms=0, num_ac_units=1,  num_fans=2),
    ]
    db.add_all(locations); db.commit()
    print(f"  OK: {len(locations)} locations")

    print("Seeding vendors...")
    vendors = [
        models.VendorModel(code="VND-001", name="ABC Stationery Supplies",  category="Stationery",         contact_person="Ramesh Kumar",   phone="9876543210", email="ramesh@abc.com",      city="Ahmedabad",   gst_no="24AABCU9603R1ZM", pan="AABCU9603R", payment_terms="Net 30", rating=4.5, status="Active"),
        models.VendorModel(code="VND-002", name="XYZ Pantry Solutions",     category="Pantry",             contact_person="Suresh Patel",   phone="9876543211", email="suresh@xyz.com",      city="Ahmedabad",   gst_no="24AABCU9604R1ZN", pan="AABCU9604R", payment_terms="Net 15", rating=4.2, status="Active"),
        models.VendorModel(code="VND-003", name="CleanCo Services",         category="Cleaning Chemicals", contact_person="Mahesh Shah",    phone="9876543212", email="mahesh@clean.com",    city="Ahmedabad",   gst_no="24AABCU9605R1ZO", pan="AABCU9605R", payment_terms="Net 30", rating=4.0, status="Active"),
        models.VendorModel(code="VND-004", name="IT Solutions India",       category="IT Consumables",     contact_person="Prakash Joshi",  phone="9876543213", email="prakash@its.com",     city="Ahmedabad",   gst_no="24AABCU9606R1ZP", pan="AABCU9606R", payment_terms="Net 45", rating=4.8, status="Active"),
        models.VendorModel(code="VND-005", name="Gujarat Electricals",      category="Electrical",         contact_person="Vijay Mehta",    phone="9876543214", email="vijay@gujelec.com",   city="Ahmedabad",   gst_no="24AABCU9607R1ZQ", pan="AABCU9607R", payment_terms="Net 30", rating=4.3, status="Active"),
        models.VendorModel(code="VND-006", name="Hygiene Hub",              category="Washroom Supplies",  contact_person="Kiran Desai",    phone="9876543215", email="kiran@hygiene.com",   city="Gandhinagar", gst_no="24AABCU9608R1ZR", pan="AABCU9608R", payment_terms="Net 15", rating=4.1, status="Active"),
        models.VendorModel(code="VND-007", name="SafetyFirst PPE",          category="PPE & Safety",       contact_person="Amit Sharma",    phone="9876543216", email="amit@safetyfirst.com",city="Ahmedabad",   gst_no="24AABCU9609R1ZS", pan="AABCU9609R", payment_terms="Net 30", rating=4.4, status="Active"),
        models.VendorModel(code="VND-008", name="Havells Distributor",      category="Electrical",         contact_person="Nitin Shah",     phone="9876543217", email="nitin@havells.com",   city="Ahmedabad",   gst_no="24AABCU9610R1ZT", pan="AABCU9610R", payment_terms="Net 30", rating=4.6, status="Active"),
        models.VendorModel(code="VND-009", name="Crompton Authorized",      category="Electrical",         contact_person="Jayesh Modi",    phone="9876543218", email="jayesh@crompton.com", city="Ahmedabad",   gst_no="24AABCU9611R1ZU", pan="AABCU9611R", payment_terms="Net 30", rating=4.5, status="Active"),
        models.VendorModel(code="VND-010", name="Anchor Dealer",            category="Electrical",         contact_person="Paresh Jain",    phone="9876543219", email="paresh@anchor.com",   city="Ahmedabad",   gst_no="24AABCU9612R1ZV", pan="AABCU9612R", payment_terms="Net 30", rating=4.4, status="Active"),
    ]
    db.add_all(vendors); db.commit()
    print(f"  OK: {len(vendors)} vendors")

    print("Seeding HK master (128 items from Excel)...")
    hk_items = [
        models.HKMasterModel(code="HK-001", name="Floor Cleaner Regular 5L", category="Cleaning Chemicals", sub_category="Floor Care", uom="Liter", eco_brand="Local", eco_price=200.0, std_brand="Lizol/Domex", std_price=320.0, prem_brand="Taski R2", prem_price=500.0, recommended="Standard", rate=320.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-002", name="Floor Cleaner Marble 5L", category="Cleaning Chemicals", sub_category="Floor Care", uom="Liter", eco_brand="Pidilite", eco_price=280.0, std_brand="Cif", std_price=420.0, prem_brand="Diversey", prem_price=650.0, recommended="Standard", rate=420.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-003", name="Glass Cleaner 5L", category="Cleaning Chemicals", sub_category="Surface Care", uom="Liter", eco_brand="Local", eco_price=100.0, std_brand="Colin", std_price=180.0, prem_brand="Diversey", prem_price=320.0, recommended="Standard", rate=180.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-004", name="Toilet Cleaner Liquid 5L", category="Cleaning Chemicals", sub_category="Washroom", uom="Liter", eco_brand="Local", eco_price=180.0, std_brand="Harpic/Domex", std_price=320.0, prem_brand="Taski Sani", prem_price=500.0, recommended="Standard", rate=320.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-005", name="Surface Disinfectant 5L", category="Cleaning Chemicals", sub_category="Disinfection", uom="Liter", eco_brand="Savlon Local", eco_price=250.0, std_brand="Dettol/Savlon", std_price=400.0, prem_brand="Diversey Oxivir", prem_price=650.0, recommended="Premium", rate=400.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-006", name="Hand Sanitizer Liquid 5L", category="Cleaning Chemicals", sub_category="Disinfection", uom="Liter", eco_brand="Local", eco_price=300.0, std_brand="Dettol/Lifebuoy", std_price=500.0, prem_brand="Purell", prem_price=800.0, recommended="Standard", rate=500.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-007", name="Phenyl White 5L", category="Cleaning Chemicals", sub_category="Disinfection", uom="Liter", eco_brand="Local", eco_price=100.0, std_brand="Lizol Phenyl", std_price=180.0, prem_brand="Harpic", prem_price=280.0, recommended="Economy", rate=180.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-008", name="Degreaser Kitchen 5L", category="Cleaning Chemicals", sub_category="Specialty", uom="Liter", eco_brand="Vim", eco_price=220.0, std_brand="Mr.Muscle", std_price=350.0, prem_brand="Suma", prem_price=580.0, recommended="Standard", rate=350.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-009", name="Hand Wash Liquid 5L", category="Washroom Supplies", sub_category="Hand Hygiene", uom="Liter", eco_brand="Godrej", eco_price=220.0, std_brand="Dettol/Lifebuoy", std_price=400.0, prem_brand="Dove", prem_price=580.0, recommended="Standard", rate=400.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-010", name="Toilet Paper Roll Regular", category="Washroom Supplies", sub_category="Paper Products", uom="Roll", eco_brand="Local", eco_price=15.0, std_brand="Bella/Shine", std_price=26.0, prem_brand="Kleenex/Scott", prem_price=48.0, recommended="Economy", rate=26.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-011", name="Toilet Paper Jumbo JRT", category="Washroom Supplies", sub_category="Paper Products", uom="Roll", eco_brand="Local", eco_price=100.0, std_brand="Euro/Majesta", std_price=180.0, prem_brand="Tork/Kimberly", prem_price=330.0, recommended="Standard", rate=180.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-012", name="Paper Towel C-Fold", category="Washroom Supplies", sub_category="Paper Products", uom="Pack", eco_brand="Local", eco_price=45.0, std_brand="Euro", std_price=80.0, prem_brand="Tork/Kleenex", prem_price=140.0, recommended="Standard", rate=80.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-013", name="Facial Tissue Box", category="Washroom Supplies", sub_category="Paper Products", uom="Box", eco_brand="Local", eco_price=45.0, std_brand="Rose Petal", std_price=75.0, prem_brand="Kleenex", prem_price=120.0, recommended="Standard", rate=75.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-014", name="Air Freshener Spray", category="Washroom Supplies", sub_category="Odor Control", uom="Can", eco_brand="Local", eco_price=100.0, std_brand="Odonil/Godrej", std_price=185.0, prem_brand="Air Wick", prem_price=330.0, recommended="Standard", rate=185.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-015", name="Urinal Screen Deodorizing", category="Washroom Supplies", sub_category="Odor Control", uom="Piece", eco_brand="Local", eco_price=55.0, std_brand="Fresh Wave", std_price=125.0, prem_brand="Big D/Wave", prem_price=240.0, recommended="Standard", rate=125.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-016", name="Soap Dispenser Manual 1L", category="Washroom Supplies", sub_category="Dispensers", uom="Piece", eco_brand="Local", eco_price=280.0, std_brand="Euro/Dolphy", std_price=625.0, prem_brand="Tork", prem_price=1500.0, recommended="Standard", rate=625.0, gst_pct=12, vendor_code="VND-006", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-017", name="Mop Cotton 400g", category="Cleaning Tools", sub_category="Mopping", uom="Piece", eco_brand="Local", eco_price=100.0, std_brand="Scotch-Brite/Gala", std_price=185.0, prem_brand="Vileda/Unger", prem_price=350.0, recommended="Economy", rate=185.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-018", name="Mop Microfiber Flat", category="Cleaning Tools", sub_category="Mopping", uom="Piece", eco_brand="Local", eco_price=200.0, std_brand="Scotch-Brite", std_price=425.0, prem_brand="Vileda", prem_price=725.0, recommended="Standard", rate=425.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-019", name="Mop Bucket with Wringer 20L", category="Cleaning Tools", sub_category="Mopping", uom="Piece", eco_brand="Local", eco_price=400.0, std_brand="Gala/Cello", std_price=750.0, prem_brand="Rubbermaid", prem_price=1500.0, recommended="Standard", rate=750.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-020", name="Broom Soft (Phool Jhadu)", category="Cleaning Tools", sub_category="Sweeping", uom="Piece", eco_brand="Local", eco_price=55.0, std_brand="Gala/Spotzero", std_price=115.0, prem_brand="Scotch-Brite", prem_price=215.0, recommended="Economy", rate=115.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-021", name="Broom Hard Plastic", category="Cleaning Tools", sub_category="Sweeping", uom="Piece", eco_brand="Local", eco_price=80.0, std_brand="Gala/Milton", std_price=165.0, prem_brand="Scotch-Brite", prem_price=300.0, recommended="Economy", rate=165.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-022", name="Dustpan Regular", category="Cleaning Tools", sub_category="Sweeping", uom="Piece", eco_brand="Local", eco_price=40.0, std_brand="Gala/Milton", std_price=95.0, prem_brand="Scotch-Brite", prem_price=185.0, recommended="Economy", rate=95.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-023", name="Scrub Pad Green Heavy Duty", category="Cleaning Tools", sub_category="Scrubbing", uom="Piece", eco_brand="Local", eco_price=12.0, std_brand="Scotch-Brite", std_price=28.0, prem_brand="3M", prem_price=58.0, recommended="Standard", rate=28.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-024", name="Cleaning Cloth Microfiber", category="Cleaning Tools", sub_category="Wiping", uom="Piece", eco_brand="Local", eco_price=40.0, std_brand="Scotch-Brite", std_price=90.0, prem_brand="Vileda/3M", prem_price=185.0, recommended="Standard", rate=90.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-025", name="Squeegee Window 35cm", category="Cleaning Tools", sub_category="Glass Cleaning", uom="Piece", eco_brand="Local", eco_price=115.0, std_brand="Gala", std_price=260.0, prem_brand="Unger/Ettore", prem_price=550.0, recommended="Standard", rate=260.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-026", name="Duster Microfiber Extendable", category="Cleaning Tools", sub_category="Dusting", uom="Piece", eco_brand="Local", eco_price=160.0, std_brand="Scotch-Brite", std_price=350.0, prem_brand="Unger", prem_price=675.0, recommended="Standard", rate=350.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-027", name="Garbage Bag Small 17x19", category="Waste Management", sub_category="Bags", uom="Kg", eco_brand="Local", eco_price=105.0, std_brand="Supreme/Time", std_price=175.0, prem_brand="Hefty", prem_price=330.0, recommended="Economy", rate=175.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-028", name="Garbage Bag Medium 19x21", category="Waste Management", sub_category="Bags", uom="Kg", eco_brand="Local", eco_price=120.0, std_brand="Supreme", std_price=215.0, prem_brand="Hefty", prem_price=370.0, recommended="Economy", rate=215.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-029", name="Garbage Bag Large 24x30", category="Waste Management", sub_category="Bags", uom="Kg", eco_brand="Local", eco_price=135.0, std_brand="Supreme", std_price=240.0, prem_brand="Hefty", prem_price=415.0, recommended="Standard", rate=240.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-030", name="Dustbin Desk 5L Open", category="Waste Management", sub_category="Bins", uom="Piece", eco_brand="Local", eco_price=70.0, std_brand="Cello/Milton", std_price=150.0, prem_brand="Rubbermaid", prem_price=340.0, recommended="Economy", rate=150.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-031", name="Dustbin Pedal 30L", category="Waste Management", sub_category="Bins", uom="Piece", eco_brand="Local", eco_price=525.0, std_brand="Cello", std_price=1025.0, prem_brand="Rubbermaid", prem_price=2150.0, recommended="Standard", rate=1025.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-032", name="Dustbin Stainless Steel 40L", category="Waste Management", sub_category="Bins", uom="Piece", eco_brand="Local", eco_price=1500.0, std_brand="Mintage", std_price=3000.0, prem_brand="Brabantia", prem_price=6750.0, recommended="Premium", rate=3000.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-001", name="Switch Modular 1 Way 6A", category="Electrical", sub_category="Switches", uom="Piece", eco_brand="Local", eco_price=25.0, std_brand="Anchor Roma", std_price=45.0, prem_brand="Legrand/Schneider", prem_price=85.0, recommended="Standard", rate=45.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-002", name="Switch Modular 2 Way 6A", category="Electrical", sub_category="Switches", uom="Piece", eco_brand="Local", eco_price=35.0, std_brand="Anchor Roma", std_price=65.0, prem_brand="Legrand/Schneider", prem_price=120.0, recommended="Standard", rate=65.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-003", name="Switch Bell Push", category="Electrical", sub_category="Switches", uom="Piece", eco_brand="Local", eco_price=30.0, std_brand="Anchor/Havells", std_price=55.0, prem_brand="Legrand", prem_price=95.0, recommended="Standard", rate=55.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-004", name="Switch 16A Power", category="Electrical", sub_category="Switches", uom="Piece", eco_brand="Local", eco_price=55.0, std_brand="Anchor/Havells", std_price=95.0, prem_brand="Legrand/Schneider", prem_price=165.0, recommended="Standard", rate=95.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-005", name="Switch 20A DP", category="Electrical", sub_category="Switches", uom="Piece", eco_brand="Local", eco_price=85.0, std_brand="Anchor/Havells", std_price=145.0, prem_brand="Legrand", prem_price=245.0, recommended="Standard", rate=145.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-006", name="Socket 5 Pin 6A", category="Electrical", sub_category="Sockets", uom="Piece", eco_brand="Local", eco_price=40.0, std_brand="Anchor Roma", std_price=70.0, prem_brand="Legrand/Schneider", prem_price=130.0, recommended="Standard", rate=70.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-007", name="Socket 5 Pin 16A", category="Electrical", sub_category="Sockets", uom="Piece", eco_brand="Local", eco_price=65.0, std_brand="Anchor/Havells", std_price=110.0, prem_brand="Legrand/Schneider", prem_price=195.0, recommended="Standard", rate=110.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-008", name="Socket USB Charger Dual", category="Electrical", sub_category="Sockets", uom="Piece", eco_brand="Local", eco_price=180.0, std_brand="Anchor/Havells", std_price=320.0, prem_brand="Legrand", prem_price=550.0, recommended="Standard", rate=320.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-009", name="Socket Computer LAN RJ45", category="Electrical", sub_category="Sockets", uom="Piece", eco_brand="Local", eco_price=80.0, std_brand="D-Link/Anchor", std_price=150.0, prem_brand="Legrand/Schneider", prem_price=280.0, recommended="Standard", rate=150.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-010", name="Socket Telephone RJ11", category="Electrical", sub_category="Sockets", uom="Piece", eco_brand="Local", eco_price=35.0, std_brand="Anchor", std_price=65.0, prem_brand="Legrand", prem_price=120.0, recommended="Standard", rate=65.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-011", name="Switch Plate 1 Module", category="Electrical", sub_category="Plates", uom="Piece", eco_brand="Local", eco_price=15.0, std_brand="Anchor Roma", std_price=28.0, prem_brand="Legrand", prem_price=55.0, recommended="Standard", rate=28.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-012", name="Switch Plate 2 Module", category="Electrical", sub_category="Plates", uom="Piece", eco_brand="Local", eco_price=20.0, std_brand="Anchor Roma", std_price=38.0, prem_brand="Legrand", prem_price=72.0, recommended="Standard", rate=38.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-013", name="Switch Plate 3 Module", category="Electrical", sub_category="Plates", uom="Piece", eco_brand="Local", eco_price=25.0, std_brand="Anchor Roma", std_price=48.0, prem_brand="Legrand", prem_price=90.0, recommended="Standard", rate=48.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-014", name="Switch Plate 4 Module", category="Electrical", sub_category="Plates", uom="Piece", eco_brand="Local", eco_price=30.0, std_brand="Anchor Roma", std_price=58.0, prem_brand="Legrand", prem_price=110.0, recommended="Standard", rate=58.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-015", name="Switch Plate 6 Module", category="Electrical", sub_category="Plates", uom="Piece", eco_brand="Local", eco_price=40.0, std_brand="Anchor Roma", std_price=75.0, prem_brand="Legrand", prem_price=145.0, recommended="Standard", rate=75.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-016", name="Switch Plate 8 Module", category="Electrical", sub_category="Plates", uom="Piece", eco_brand="Local", eco_price=55.0, std_brand="Anchor Roma", std_price=100.0, prem_brand="Legrand", prem_price=195.0, recommended="Standard", rate=100.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-017", name="Switch Plate 12 Module", category="Electrical", sub_category="Plates", uom="Piece", eco_brand="Local", eco_price=75.0, std_brand="Anchor Roma", std_price=140.0, prem_brand="Legrand", prem_price=275.0, recommended="Standard", rate=140.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-018", name="LED Bulb 7W B22", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=45.0, std_brand="Wipro/Syska", std_price=85.0, prem_brand="Philips/Havells", prem_price=140.0, recommended="Standard", rate=85.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-019", name="LED Bulb 9W B22", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=55.0, std_brand="Wipro/Syska", std_price=100.0, prem_brand="Philips/Havells", prem_price=165.0, recommended="Standard", rate=100.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-020", name="LED Bulb 12W B22", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=70.0, std_brand="Wipro/Syska", std_price=125.0, prem_brand="Philips/Havells", prem_price=210.0, recommended="Standard", rate=125.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-021", name="LED Bulb 15W B22", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=90.0, std_brand="Wipro/Syska", std_price=155.0, prem_brand="Philips/Havells", prem_price=265.0, recommended="Standard", rate=155.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-022", name="LED Bulb 18W/20W B22", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=115.0, std_brand="Wipro/Syska", std_price=195.0, prem_brand="Philips/Havells", prem_price=330.0, recommended="Standard", rate=195.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-023", name="LED Tube Light 20W 4ft", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=150.0, std_brand="Wipro/Syska", std_price=280.0, prem_brand="Philips/Havells", prem_price=450.0, recommended="Standard", rate=280.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-024", name="LED Tube Light 10W 2ft", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=100.0, std_brand="Wipro/Syska", std_price=180.0, prem_brand="Philips/Havells", prem_price=300.0, recommended="Standard", rate=180.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-025", name="LED Panel Light Round 6W", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=120.0, std_brand="Wipro/Syska", std_price=220.0, prem_brand="Philips/Havells", prem_price=380.0, recommended="Standard", rate=220.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-026", name="LED Panel Light Round 12W", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=180.0, std_brand="Wipro/Syska", std_price=320.0, prem_brand="Philips/Havells", prem_price=550.0, recommended="Standard", rate=320.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-027", name="LED Panel Light Round 18W", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=250.0, std_brand="Wipro/Syska", std_price=450.0, prem_brand="Philips/Havells", prem_price=750.0, recommended="Standard", rate=450.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-028", name="LED Panel Light 2x2 36W", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=650.0, std_brand="Wipro/Syska", std_price=1100.0, prem_brand="Philips/Havells", prem_price=1800.0, recommended="Standard", rate=1100.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-029", name="LED Flood Light 30W", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=450.0, std_brand="Wipro/Syska", std_price=850.0, prem_brand="Philips/Havells", prem_price=1400.0, recommended="Standard", rate=850.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-030", name="LED Flood Light 50W", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=700.0, std_brand="Wipro/Syska", std_price=1300.0, prem_brand="Philips/Havells", prem_price=2200.0, recommended="Standard", rate=1300.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-031", name="Emergency Light LED", category="Electrical", sub_category="Lighting", uom="Piece", eco_brand="Local", eco_price=350.0, std_brand="Wipro/Syska", std_price=650.0, prem_brand="Philips/Havells", prem_price=1100.0, recommended="Standard", rate=650.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-032", name="Ceiling Fan 48 inch", category="Electrical", sub_category="Fans", uom="Piece", eco_brand="Local", eco_price=1200.0, std_brand="Havells/Crompton", std_price=2200.0, prem_brand="Orient/Usha", prem_price=3500.0, recommended="Standard", rate=2200.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-033", name="Ceiling Fan 56 inch", category="Electrical", sub_category="Fans", uom="Piece", eco_brand="Local", eco_price=1400.0, std_brand="Havells/Crompton", std_price=2600.0, prem_brand="Orient/Usha", prem_price=4200.0, recommended="Standard", rate=2600.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-034", name="Exhaust Fan 6 inch", category="Electrical", sub_category="Fans", uom="Piece", eco_brand="Local", eco_price=500.0, std_brand="Havells/Crompton", std_price=950.0, prem_brand="Panasonic", prem_price=1600.0, recommended="Standard", rate=950.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-035", name="Exhaust Fan 9 inch", category="Electrical", sub_category="Fans", uom="Piece", eco_brand="Local", eco_price=750.0, std_brand="Havells/Crompton", std_price=1400.0, prem_brand="Panasonic", prem_price=2400.0, recommended="Standard", rate=1400.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-036", name="Exhaust Fan 12 inch", category="Electrical", sub_category="Fans", uom="Piece", eco_brand="Local", eco_price=1100.0, std_brand="Havells/Crompton", std_price=2000.0, prem_brand="Panasonic", prem_price=3500.0, recommended="Standard", rate=2000.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-037", name="Table Fan 16 inch", category="Electrical", sub_category="Fans", uom="Piece", eco_brand="Local", eco_price=1000.0, std_brand="Havells/Crompton", std_price=1800.0, prem_brand="Orient/Usha", prem_price=2800.0, recommended="Standard", rate=1800.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-038", name="Pedestal Fan 16 inch", category="Electrical", sub_category="Fans", uom="Piece", eco_brand="Local", eco_price=1400.0, std_brand="Havells/Crompton", std_price=2500.0, prem_brand="Orient/Usha", prem_price=4000.0, recommended="Standard", rate=2500.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-039", name="Wire 1 sq mm FR", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=8.0, std_brand="Havells/Polycab", std_price=14.0, prem_brand="Finolex", prem_price=20.0, recommended="Standard", rate=14.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-040", name="Wire 1.5 sq mm FR", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=12.0, std_brand="Havells/Polycab", std_price=20.0, prem_brand="Finolex", prem_price=28.0, recommended="Standard", rate=20.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-041", name="Wire 2.5 sq mm FR", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=18.0, std_brand="Havells/Polycab", std_price=32.0, prem_brand="Finolex", prem_price=45.0, recommended="Standard", rate=32.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-042", name="Wire 4 sq mm FR", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=28.0, std_brand="Havells/Polycab", std_price=50.0, prem_brand="Finolex", prem_price=72.0, recommended="Standard", rate=50.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-043", name="Wire 6 sq mm FR", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=42.0, std_brand="Havells/Polycab", std_price=75.0, prem_brand="Finolex", prem_price=108.0, recommended="Standard", rate=75.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-044", name="Flexible Wire 23/36", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=15.0, std_brand="Havells/Polycab", std_price=28.0, prem_brand="Finolex", prem_price=42.0, recommended="Standard", rate=28.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-045", name="3 Core Wire 1.5 sq mm", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=40.0, std_brand="Havells/Polycab", std_price=70.0, prem_brand="Finolex", prem_price=100.0, recommended="Standard", rate=70.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-046", name="Ethernet Cable Cat6", category="Electrical", sub_category="Wiring", uom="Meter", eco_brand="Local", eco_price=12.0, std_brand="D-Link/Anchor", std_price=22.0, prem_brand="Commscope/Legrand", prem_price=38.0, recommended="Standard", rate=22.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-047", name="MCB Single Pole 6A", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=80.0, std_brand="Havells/L&T", std_price=145.0, prem_brand="Schneider/ABB", prem_price=250.0, recommended="Standard", rate=145.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-048", name="MCB Single Pole 16A", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=85.0, std_brand="Havells/L&T", std_price=155.0, prem_brand="Schneider/ABB", prem_price=270.0, recommended="Standard", rate=155.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-049", name="MCB Single Pole 32A", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=100.0, std_brand="Havells/L&T", std_price=180.0, prem_brand="Schneider/ABB", prem_price=320.0, recommended="Standard", rate=180.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-050", name="MCB Double Pole 32A", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=250.0, std_brand="Havells/L&T", std_price=450.0, prem_brand="Schneider/ABB", prem_price=780.0, recommended="Standard", rate=450.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-051", name="MCB Triple Pole 32A", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=450.0, std_brand="Havells/L&T", std_price=800.0, prem_brand="Schneider/ABB", prem_price=1400.0, recommended="Standard", rate=800.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-052", name="RCCB 40A 30mA 2P", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=800.0, std_brand="Havells/L&T", std_price=1400.0, prem_brand="Schneider/ABB", prem_price=2400.0, recommended="Standard", rate=1400.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-053", name="RCCB 63A 30mA 4P", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=2200.0, std_brand="Havells/L&T", std_price=3800.0, prem_brand="Schneider/ABB", prem_price=6500.0, recommended="Standard", rate=3800.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-054", name="Distribution Box 4 Way", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=180.0, std_brand="Havells/L&T", std_price=350.0, prem_brand="Schneider", prem_price=600.0, recommended="Standard", rate=350.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-055", name="Distribution Box 8 Way", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=350.0, std_brand="Havells/L&T", std_price=650.0, prem_brand="Schneider", prem_price=1100.0, recommended="Standard", rate=650.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-056", name="Distribution Box 12 Way", category="Electrical", sub_category="Protection", uom="Piece", eco_brand="Local", eco_price=550.0, std_brand="Havells/L&T", std_price=1000.0, prem_brand="Schneider", prem_price=1700.0, recommended="Standard", rate=1000.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-057", name="PVC Conduit 20mm", category="Electrical", sub_category="Conduits", uom="Meter", eco_brand="Local", eco_price=18.0, std_brand="Precision/Supreme", std_price=32.0, prem_brand="Finolex", prem_price=48.0, recommended="Standard", rate=32.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-058", name="PVC Conduit 25mm", category="Electrical", sub_category="Conduits", uom="Meter", eco_brand="Local", eco_price=25.0, std_brand="Precision/Supreme", std_price=45.0, prem_brand="Finolex", prem_price=68.0, recommended="Standard", rate=45.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-059", name="Conduit Bend 20mm", category="Electrical", sub_category="Conduits", uom="Piece", eco_brand="Local", eco_price=8.0, std_brand="Precision", std_price=15.0, prem_brand="Finolex", prem_price=25.0, recommended="Standard", rate=15.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-060", name="Junction Box Deep", category="Electrical", sub_category="Conduits", uom="Piece", eco_brand="Local", eco_price=12.0, std_brand="Precision", std_price=22.0, prem_brand="Finolex", prem_price=38.0, recommended="Standard", rate=22.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-061", name="Casing Capping 1 inch", category="Electrical", sub_category="Conduits", uom="Meter", eco_brand="Local", eco_price=20.0, std_brand="Supreme", std_price=35.0, prem_brand="Finolex", prem_price=55.0, recommended="Standard", rate=35.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-062", name="Extension Board 4+1", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=180.0, std_brand="Anchor/Havells", std_price=350.0, prem_brand="Belkin/APC", prem_price=650.0, recommended="Standard", rate=350.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-063", name="Extension Board 6+1", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=250.0, std_brand="Anchor/Havells", std_price=480.0, prem_brand="Belkin/APC", prem_price=900.0, recommended="Standard", rate=480.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-064", name="Extension Cord 5m", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=150.0, std_brand="Anchor/Havells", std_price=280.0, prem_brand="Belkin", prem_price=500.0, recommended="Standard", rate=280.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-065", name="3 Pin Plug Top 6A", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=15.0, std_brand="Anchor/Havells", std_price=30.0, prem_brand="Legrand", prem_price=55.0, recommended="Standard", rate=30.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-066", name="3 Pin Plug Top 16A", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=25.0, std_brand="Anchor/Havells", std_price=50.0, prem_brand="Legrand", prem_price=90.0, recommended="Standard", rate=50.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-067", name="Bulb Holder B22", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=12.0, std_brand="Anchor/Havells", std_price=25.0, prem_brand="Legrand", prem_price=45.0, recommended="Standard", rate=25.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-068", name="Tube Light Holder Set", category="Electrical", sub_category="Accessories", uom="Set", eco_brand="Local", eco_price=35.0, std_brand="Anchor/Havells", std_price=65.0, prem_brand="Philips", prem_price=110.0, recommended="Standard", rate=65.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-069", name="Starter Tube Light S2", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=8.0, std_brand="Philips/Wipro", std_price=18.0, prem_brand="Osram", prem_price=32.0, recommended="Economy", rate=18.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-070", name="Choke/Ballast 36W", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=60.0, std_brand="Philips/Wipro", std_price=120.0, prem_brand="Osram", prem_price=200.0, recommended="Standard", rate=120.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-071", name="Electrical Tape 18mm", category="Electrical", sub_category="Accessories", uom="Roll", eco_brand="Local", eco_price=12.0, std_brand="3M/Anchor", std_price=28.0, prem_brand="3M Temflex", prem_price=48.0, recommended="Standard", rate=28.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-072", name="Cable Tie 4 inch", category="Electrical", sub_category="Accessories", uom="Pack", eco_brand="Local", eco_price=30.0, std_brand="HellermannTyton", std_price=60.0, prem_brand="Panduit", prem_price=100.0, recommended="Standard", rate=60.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-073", name="Cable Tie 8 inch", category="Electrical", sub_category="Accessories", uom="Pack", eco_brand="Local", eco_price=50.0, std_brand="HellermannTyton", std_price=100.0, prem_brand="Panduit", prem_price=170.0, recommended="Standard", rate=100.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-074", name="Spike Guard 6 Socket", category="Electrical", sub_category="Accessories", uom="Piece", eco_brand="Local", eco_price=250.0, std_brand="Belkin/APC", std_price=550.0, prem_brand="Legrand", prem_price=950.0, recommended="Standard", rate=550.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-075", name="UPS 600VA", category="Electrical", sub_category="Power Backup", uom="Piece", eco_brand="Local", eco_price=2500.0, std_brand="Microtek/Luminous", std_price=4500.0, prem_brand="APC/Numeric", prem_price=7500.0, recommended="Standard", rate=4500.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-076", name="UPS 1KVA", category="Electrical", sub_category="Power Backup", uom="Piece", eco_brand="Local", eco_price=5500.0, std_brand="Microtek/Luminous", std_price=9500.0, prem_brand="APC/Numeric", prem_price=16000.0, recommended="Standard", rate=9500.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="EL-077", name="Stabilizer 1KVA", category="Electrical", sub_category="Power Backup", uom="Piece", eco_brand="Local", eco_price=2000.0, std_brand="V-Guard/Microtek", std_price=3500.0, prem_brand="APC", prem_price=6000.0, recommended="Standard", rate=3500.0, gst_pct=18, vendor_code="VND-008", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-033", name="Tea Premium (Wagh Bakri)", category="Pantry", sub_category="Beverages", uom="Kg", eco_brand="Wagh Bakri", eco_price=400.0, std_brand="Tata Tea Gold", std_price=575.0, prem_brand="Taj Mahal", prem_price=850.0, recommended="Standard", rate=575.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-034", name="Tea Bags Box 100", category="Pantry", sub_category="Beverages", uom="Box", eco_brand="Local", eco_price=150.0, std_brand="Lipton/Tetley", std_price=260.0, prem_brand="Twinings", prem_price=525.0, recommended="Standard", rate=260.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-035", name="Coffee Instant 200g", category="Pantry", sub_category="Beverages", uom="Jar", eco_brand="Local", eco_price=230.0, std_brand="Nescafe Classic", std_price=400.0, prem_brand="Bru Gold", prem_price=330.0, recommended="Standard", rate=400.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-036", name="Sugar White", category="Pantry", sub_category="Sweeteners", uom="Kg", eco_brand="Local", eco_price=48.0, std_brand="Dhampure/Trust", std_price=55.0, prem_brand="Organic", prem_price=100.0, recommended="Economy", rate=55.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-037", name="Milk Tetra Pack 1L", category="Pantry", sub_category="Dairy", uom="Liter", eco_brand="Local", eco_price=62.0, std_brand="Amul/Verka", std_price=70.0, prem_brand="Nestle", prem_price=85.0, recommended="Standard", rate=70.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-038", name="Paper Cup 150ml", category="Pantry", sub_category="Disposables", uom="Pack", eco_brand="Local", eco_price=75.0, std_brand="Nice/Brillware", std_price=125.0, prem_brand="Dixie", prem_price=230.0, recommended="Economy", rate=125.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-039", name="Water Jar 20L Refill", category="Pantry", sub_category="Water", uom="Jar", eco_brand="Local", eco_price=45.0, std_brand="Bisleri/Kinley", std_price=72.0, prem_brand="Aquafina", prem_price=88.0, recommended="Standard", rate=72.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-040", name="Water Bottle 1L Case", category="Pantry", sub_category="Water", uom="Case", eco_brand="Local", eco_price=150.0, std_brand="Bisleri/Kinley", std_price=215.0, prem_brand="Aquafina", prem_price=375.0, recommended="Standard", rate=215.0, gst_pct=5, vendor_code="VND-002", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-041", name="Gloves Rubber Household", category="PPE & Safety", sub_category="Hand Protection", uom="Pair", eco_brand="Local", eco_price=45.0, std_brand="Scotch-Brite/Gala", std_price=90.0, prem_brand="Vileda", prem_price=185.0, recommended="Standard", rate=90.0, gst_pct=18, vendor_code="VND-007", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-042", name="Gloves Nitrile Disposable", category="PPE & Safety", sub_category="Hand Protection", uom="Box", eco_brand="Local", eco_price=340.0, std_brand="Supermax", std_price=525.0, prem_brand="Ansell", prem_price=825.0, recommended="Standard", rate=525.0, gst_pct=18, vendor_code="VND-007", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-043", name="Safety Shoes Gumboot", category="PPE & Safety", sub_category="Foot Protection", uom="Pair", eco_brand="Local", eco_price=325.0, std_brand="Hillson/Action", std_price=625.0, prem_brand="Bata", prem_price=1150.0, recommended="Standard", rate=625.0, gst_pct=18, vendor_code="VND-007", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-044", name="Face Mask Surgical 3-ply", category="PPE & Safety", sub_category="Respiratory", uom="Box", eco_brand="Local", eco_price=105.0, std_brand="Venus/Magnum", std_price=185.0, prem_brand="3M", prem_price=340.0, recommended="Standard", rate=185.0, gst_pct=18, vendor_code="VND-007", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-045", name="Caution Sign Wet Floor", category="PPE & Safety", sub_category="Safety Signs", uom="Piece", eco_brand="Local", eco_price=215.0, std_brand="Gala/Euro", std_price=465.0, prem_brand="Rubbermaid", prem_price=850.0, recommended="Standard", rate=465.0, gst_pct=18, vendor_code="VND-007", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-046", name="First Aid Kit Office", category="PPE & Safety", sub_category="Safety", uom="Kit", eco_brand="Local", eco_price=650.0, std_brand="St.John/Acme", std_price=1250.0, prem_brand="Honeywell", prem_price=2500.0, recommended="Standard", rate=1250.0, gst_pct=18, vendor_code="VND-007", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-047", name="Cockroach Killer Spray", category="Pest Control", sub_category="Insecticide", uom="Can", eco_brand="Laxman Rekha", eco_price=105.0, std_brand="Hit/Mortein", std_price=230.0, prem_brand="Baygon", prem_price=315.0, recommended="Standard", rate=230.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-048", name="Cockroach Gel 20g", category="Pest Control", sub_category="Insecticide", uom="Tube", eco_brand="Local", eco_price=140.0, std_brand="Maxforce/Advion", std_price=450.0, prem_brand="Bayer Gel", prem_price=625.0, recommended="Premium", rate=450.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-049", name="Mosquito Liquid Refill", category="Pest Control", sub_category="Insecticide", uom="Refill", eco_brand="Local", eco_price=65.0, std_brand="Good Knight/All Out", std_price=115.0, prem_brand="Mortein", prem_price=150.0, recommended="Standard", rate=115.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-050", name="Fly Catcher Electric UV", category="Pest Control", sub_category="Trap", uom="Piece", eco_brand="Local", eco_price=1150.0, std_brand="Ecofly/Genus", std_price=2750.0, prem_brand="Rentokil", prem_price=6500.0, recommended="Standard", rate=2750.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),
        models.HKMasterModel(code="HK-051", name="Rat Trap Mechanical", category="Pest Control", sub_category="Trap", uom="Piece", eco_brand="Local", eco_price=75.0, std_brand="Victor", std_price=200.0, prem_brand="Tomcat", prem_price=375.0, recommended="Standard", rate=200.0, gst_pct=18, vendor_code="VND-003", rol=20, max_stock=100, lead_days=5, status="Active"),    ]
    db.add_all(hk_items); db.commit()
    print(f"  OK: {len(hk_items)} HK master items")

    print("Seeding active item master (16 items)...")
    items = [
        models.ItemModel(code="HK-001", name="Floor Cleaner Regular 5L",  category="Cleaning Chemicals", sub_category="Floor Care",      uom="Liter", brand_tier="Standard", vendor_code="VND-003", rate=310,  gst_pct=18, rol=20,  max_stock=100, lead_days=5, status="Active"),
        models.ItemModel(code="HK-004", name="Toilet Cleaner Liquid 5L",  category="Cleaning Chemicals", sub_category="Washroom",        uom="Liter", brand_tier="Standard", vendor_code="VND-003", rate=300,  gst_pct=18, rol=15,  max_stock=80,  lead_days=5, status="Active"),
        models.ItemModel(code="HK-009", name="Hand Wash Liquid 5L",       category="Washroom Supplies",  sub_category="Hand Hygiene",    uom="Liter", brand_tier="Standard", vendor_code="VND-006", rate=380,  gst_pct=12, rol=15,  max_stock=60,  lead_days=5, status="Active"),
        models.ItemModel(code="HK-010", name="Toilet Paper Roll Regular", category="Washroom Supplies",  sub_category="Paper Products",  uom="Roll",  brand_tier="Economy",  vendor_code="VND-006", rate=14,   gst_pct=12, rol=100, max_stock=500, lead_days=3, status="Active"),
        models.ItemModel(code="HK-017", name="Mop Cotton 400g",           category="Cleaning Tools",     sub_category="Mopping",         uom="Piece", brand_tier="Economy",  vendor_code="VND-003", rate=95,   gst_pct=18, rol=15,  max_stock=50,  lead_days=5, status="Active"),
        models.ItemModel(code="HK-027", name="Garbage Bag Small 17x19",   category="Waste Management",   sub_category="Bags",            uom="Kg",    brand_tier="Economy",  vendor_code="VND-003", rate=100,  gst_pct=18, rol=20,  max_stock=80,  lead_days=5, status="Active"),
        models.ItemModel(code="HK-033", name="Tea Premium (Wagh Bakri)",  category="Pantry",             sub_category="Beverages",       uom="Kg",    brand_tier="Standard", vendor_code="VND-002", rate=560,  gst_pct=5,  rol=10,  max_stock=30,  lead_days=3, status="Active"),
        models.ItemModel(code="HK-036", name="Sugar White",               category="Pantry",             sub_category="Sweeteners",      uom="Kg",    brand_tier="Economy",  vendor_code="VND-002", rate=46,   gst_pct=5,  rol=25,  max_stock=100, lead_days=3, status="Active"),
        models.ItemModel(code="EL-001", name="Switch Modular 1 Way 6A",   category="Electrical",         sub_category="Switches",        uom="Piece", brand_tier="Standard", vendor_code="VND-010", rate=42,   gst_pct=18, rol=30,  max_stock=100, lead_days=5, status="Active"),
        models.ItemModel(code="EL-006", name="Socket 5 Pin 6A",           category="Electrical",         sub_category="Sockets",         uom="Piece", brand_tier="Standard", vendor_code="VND-010", rate=65,   gst_pct=18, rol=25,  max_stock=80,  lead_days=5, status="Active"),
        models.ItemModel(code="EL-019", name="LED Bulb 9W B22",           category="Electrical",         sub_category="Lighting",        uom="Piece", brand_tier="Standard", vendor_code="VND-008", rate=95,   gst_pct=18, rol=50,  max_stock=200, lead_days=5, status="Active"),
        models.ItemModel(code="EL-023", name="LED Tube Light 20W 4ft",    category="Electrical",         sub_category="Lighting",        uom="Piece", brand_tier="Standard", vendor_code="VND-008", rate=265,  gst_pct=18, rol=30,  max_stock=100, lead_days=5, status="Active"),
        models.ItemModel(code="EL-034", name="Ceiling Fan 48 inch",       category="Electrical",         sub_category="Fans",            uom="Piece", brand_tier="Standard", vendor_code="VND-009", rate=2200, gst_pct=18, rol=5,   max_stock=15,  lead_days=7, status="Active"),
        models.ItemModel(code="EL-041", name="Wire 2.5 sq mm FR",         category="Electrical",         sub_category="Wiring",          uom="Meter", brand_tier="Standard", vendor_code="VND-005", rate=32,   gst_pct=18, rol=200, max_stock=500, lead_days=5, status="Active"),
        models.ItemModel(code="EL-049", name="MCB Single Pole 32A",       category="Electrical",         sub_category="Protection",      uom="Piece", brand_tier="Standard", vendor_code="VND-008", rate=180,  gst_pct=18, rol=20,  max_stock=60,  lead_days=5, status="Active"),
        models.ItemModel(code="HK-041", name="Gloves Rubber Household",   category="PPE & Safety",       sub_category="Hand Protection", uom="Pair",  brand_tier="Standard", vendor_code="VND-007", rate=85,   gst_pct=18, rol=30,  max_stock=100, lead_days=5, status="Active"),
    ]
    db.add_all(items); db.commit()
    print(f"  OK: {len(items)} active items")

    print("Seeding inventory, PRs, POs, GRNs, issuances...")
    inventory = [
        models.InventoryModel(item_code="HK-001", location_code="STORE-CH", vendor_code="VND-003", rate=310,  opening_stock=50,  stock_in=20, stock_out=10),
        models.InventoryModel(item_code="HK-004", location_code="STORE-CH", vendor_code="VND-003", rate=300,  opening_stock=40,  stock_in=0,  stock_out=5),
        models.InventoryModel(item_code="HK-009", location_code="STORE-CH", vendor_code="VND-006", rate=380,  opening_stock=30,  stock_in=0,  stock_out=0),
        models.InventoryModel(item_code="HK-010", location_code="STORE-CH", vendor_code="VND-006", rate=14,   opening_stock=300, stock_in=0,  stock_out=50),
        models.InventoryModel(item_code="HK-017", location_code="STORE-CH", vendor_code="VND-003", rate=95,   opening_stock=30,  stock_in=0,  stock_out=0),
        models.InventoryModel(item_code="HK-027", location_code="STORE-CH", vendor_code="VND-003", rate=100,  opening_stock=40,  stock_in=0,  stock_out=8),
        models.InventoryModel(item_code="HK-033", location_code="CH-1B",    vendor_code="VND-002", rate=560,  opening_stock=15,  stock_in=10, stock_out=3),
        models.InventoryModel(item_code="HK-036", location_code="CH-1B",    vendor_code="VND-002", rate=46,   opening_stock=50,  stock_in=0,  stock_out=0),
        models.InventoryModel(item_code="EL-001", location_code="STORE-CH", vendor_code="VND-010", rate=42,   opening_stock=50,  stock_in=0,  stock_out=10),
        models.InventoryModel(item_code="EL-006", location_code="STORE-CH", vendor_code="VND-010", rate=65,   opening_stock=40,  stock_in=0,  stock_out=0),
        models.InventoryModel(item_code="EL-019", location_code="STORE-CH", vendor_code="VND-008", rate=95,   opening_stock=60,  stock_in=48, stock_out=25),
        models.InventoryModel(item_code="EL-023", location_code="STORE-CH", vendor_code="VND-008", rate=265,  opening_stock=40,  stock_in=20, stock_out=8),
        models.InventoryModel(item_code="EL-034", location_code="STORE-CH", vendor_code="VND-009", rate=2200, opening_stock=8,   stock_in=0,  stock_out=0),
        models.InventoryModel(item_code="EL-041", location_code="STORE-CH", vendor_code="VND-005", rate=32,   opening_stock=300, stock_in=0,  stock_out=0),
        models.InventoryModel(item_code="EL-049", location_code="STORE-CH", vendor_code="VND-008", rate=180,  opening_stock=30,  stock_in=0,  stock_out=5),
        models.InventoryModel(item_code="HK-041", location_code="STORE-CH", vendor_code="VND-007", rate=85,   opening_stock=60,  stock_in=0,  stock_out=0),
    ]
    db.add_all(inventory); db.commit()

    prs = [
        models.PurchaseRequisitionModel(pr_no="PR-2024-001", pr_date=date(2024,1,2),  item_code="HK-001", req_qty=20,  location_code="CH-1B",  department="Admin",       requested_by="Store Keeper",    priority="Urgent", required_date=date(2024,1,5),  justification="Monthly stock replenishment",   status="Approved",  approved_by="Admin Head", approval_date=date(2024,1,3),  po_ref="PO-2024-001"),
        models.PurchaseRequisitionModel(pr_no="PR-2024-002", pr_date=date(2024,1,3),  item_code="EL-019", req_qty=50,  location_code="CH-1B",  department="Maintenance",  requested_by="Electrician",     priority="Normal", required_date=date(2024,1,10), justification="Bulb replacement across floors", status="Approved",  approved_by="Admin Head", approval_date=date(2024,1,4),  po_ref="PO-2024-002"),
        models.PurchaseRequisitionModel(pr_no="PR-2024-003", pr_date=date(2024,1,5),  item_code="HK-033", req_qty=10,  location_code="CH-1B",  department="Admin",       requested_by="Pantry Incharge", priority="Normal", required_date=date(2024,1,10), justification="Tea stock for pantry",          status="Approved",  approved_by="Dept Head",  approval_date=date(2024,1,6),  po_ref="PO-2024-003"),
        models.PurchaseRequisitionModel(pr_no="PR-2024-004", pr_date=date(2024,1,8),  item_code="EL-023", req_qty=30,  location_code="CH-2B",  department="Maintenance",  requested_by="Electrician",     priority="High",   required_date=date(2024,1,12), justification="Tube light replacement",        status="Approved",  approved_by="Admin Head", approval_date=date(2024,1,9),  po_ref="PO-2024-004"),
        models.PurchaseRequisitionModel(pr_no="PR-2024-005", pr_date=date(2024,1,10), item_code="HK-010", req_qty=200, location_code="CH-1B",  department="Housekeeping", requested_by="HK Supervisor",   priority="Normal", required_date=date(2024,1,15), justification="Toilet paper monthly stock",    status="Approved",  approved_by="Dept Head",  approval_date=date(2024,1,11), po_ref="PO-2024-005"),
        models.PurchaseRequisitionModel(pr_no="PR-2024-006", pr_date=date(2024,1,12), item_code="EL-001", req_qty=50,  location_code="MS",     department="Maintenance",  requested_by="Site Electrician",priority="Normal", required_date=date(2024,1,18), justification="Switch replacement",            status="Submitted"),
        models.PurchaseRequisitionModel(pr_no="PR-2024-007", pr_date=date(2024,1,15), item_code="HK-041", req_qty=30,  location_code="CH-1B",  department="Housekeeping", requested_by="HK Supervisor",   priority="Low",    required_date=date(2024,1,22), justification="Gloves for HK staff",           status="Draft"),
    ]
    db.add_all(prs); db.commit()

    pos = [
        models.PurchaseOrderModel(po_no="PO-2024-001", po_date=date(2024,1,3),  pr_ref="PR-2024-001", vendor_code="VND-003", item_code="HK-001", uom="Liter", qty_ordered=20,  rate=310,  gst_pct=18, delivery_date=date(2024,1,8),  delivery_location="STORE-CH", terms="Net 30", status="Fully Received",   received_qty=20,  balance_qty=0),
        models.PurchaseOrderModel(po_no="PO-2024-002", po_date=date(2024,1,4),  pr_ref="PR-2024-002", vendor_code="VND-008", item_code="EL-019", uom="Piece", qty_ordered=50,  rate=95,   gst_pct=18, delivery_date=date(2024,1,12), delivery_location="STORE-CH", terms="Net 30", status="Fully Received",   received_qty=50,  balance_qty=0),
        models.PurchaseOrderModel(po_no="PO-2024-003", po_date=date(2024,1,6),  pr_ref="PR-2024-003", vendor_code="VND-002", item_code="HK-033", uom="Kg",    qty_ordered=10,  rate=560,  gst_pct=5,  delivery_date=date(2024,1,12), delivery_location="CH-1B",    terms="Net 15", status="Fully Received",   received_qty=10,  balance_qty=0),
        models.PurchaseOrderModel(po_no="PO-2024-004", po_date=date(2024,1,9),  pr_ref="PR-2024-004", vendor_code="VND-008", item_code="EL-023", uom="Piece", qty_ordered=30,  rate=265,  gst_pct=18, delivery_date=date(2024,1,15), delivery_location="STORE-CH", terms="Net 30", status="Partial Received", received_qty=20,  balance_qty=10),
        models.PurchaseOrderModel(po_no="PO-2024-005", po_date=date(2024,1,11), pr_ref="PR-2024-005", vendor_code="VND-006", item_code="HK-010", uom="Roll",  qty_ordered=200, rate=14,   gst_pct=12, delivery_date=date(2024,1,18), delivery_location="STORE-CH", terms="Net 15", status="Sent to Vendor",   received_qty=0,   balance_qty=200),
    ]
    db.add_all(pos); db.commit()

    grns = [
        models.GRNModel(grn_no="GRN-2024-001", grn_date=date(2024,1,8),  invoice_no="INV-V3-1001", po_no="PO-2024-001", vendor_code="VND-003", item_code="HK-001", recd_qty=20, accepted_qty=20, rejected_qty=0, uom="Liter", rate=310, received_by="Store Keeper", inspected_by="QC Officer",  store_location="STORE-CH", batch_lot="B001", status="Stored",  remarks="Quality OK"),
        models.GRNModel(grn_no="GRN-2024-002", grn_date=date(2024,1,12), invoice_no="INV-V8-2001", po_no="PO-2024-002", vendor_code="VND-008", item_code="EL-019", recd_qty=50, accepted_qty=48, rejected_qty=2, uom="Piece", rate=95,  received_by="Store Keeper", inspected_by="Electrician", store_location="STORE-CH", batch_lot="B002", status="Stored",  remarks="2 pcs damaged"),
        models.GRNModel(grn_no="GRN-2024-003", grn_date=date(2024,1,12), invoice_no="INV-V2-1501", po_no="PO-2024-003", vendor_code="VND-002", item_code="HK-033", recd_qty=10, accepted_qty=10, rejected_qty=0, uom="Kg",    rate=560, received_by="Pantry Staff", inspected_by="Admin",      store_location="CH-1B",    batch_lot="B003", status="Stored",  remarks="Fresh stock"),
        models.GRNModel(grn_no="GRN-2024-004", grn_date=date(2024,1,15), invoice_no="INV-V8-2002", po_no="PO-2024-004", vendor_code="VND-008", item_code="EL-023", recd_qty=20, accepted_qty=20, rejected_qty=0, uom="Piece", rate=265, received_by="Store Keeper", inspected_by="Electrician", store_location="STORE-CH", batch_lot="B004", status="Stored",  remarks="Partial delivery"),
    ]
    db.add_all(grns); db.commit()

    issuances = [
        models.IssuanceLogModel(issue_id="ISS-001", date=date(2024,1,10), month=1, quarter=1, item_code="HK-001", qty=10, uom="Liter", rate=310, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff",      issued_by="Store Keeper", remarks="Floor cleaning supply"),
        models.IssuanceLogModel(issue_id="ISS-002", date=date(2024,1,12), month=1, quarter=1, item_code="EL-019", qty=15, uom="Piece", rate=95,  location_code="STORE-CH", department="Maintenance",  issued_to="Electrician",   issued_by="Store Keeper", remarks="Bulb replacement CH-1B"),
        models.IssuanceLogModel(issue_id="ISS-003", date=date(2024,1,13), month=1, quarter=1, item_code="HK-033", qty=3,  uom="Kg",    rate=560, location_code="CH-1B",    department="Admin",        issued_to="Pantry Staff",  issued_by="Admin",        remarks="Tea for pantry"),
        models.IssuanceLogModel(issue_id="ISS-004", date=date(2024,1,15), month=1, quarter=1, item_code="EL-023", qty=8,  uom="Piece", rate=265, location_code="STORE-CH", department="Maintenance",  issued_to="Electrician",   issued_by="Store Keeper", remarks="Tube replacement CH-2B"),
        models.IssuanceLogModel(issue_id="ISS-005", date=date(2024,1,16), month=1, quarter=1, item_code="HK-010", qty=50, uom="Roll",  rate=14,  location_code="STORE-CH", department="Housekeeping", issued_to="HK Supervisor", issued_by="Store Keeper", remarks="Weekly stock"),
        models.IssuanceLogModel(issue_id="ISS-006", date=date(2024,1,18), month=1, quarter=1, item_code="EL-001", qty=10, uom="Piece", rate=42,  location_code="STORE-CH", department="Maintenance",  issued_to="Electrician",   issued_by="Store Keeper", remarks="Switch replacement"),
        models.IssuanceLogModel(issue_id="ISS-007", date=date(2024,1,20), month=1, quarter=1, item_code="HK-004", qty=5,  uom="Liter", rate=300, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff",      issued_by="Store Keeper", remarks="Toilet cleaner"),
        models.IssuanceLogModel(issue_id="ISS-008", date=date(2024,1,22), month=1, quarter=1, item_code="EL-019", qty=10, uom="Piece", rate=95,  location_code="STORE-CH", department="Maintenance",  issued_to="Electrician",   issued_by="Store Keeper", remarks="Bulb replacement CH-3B1"),
        models.IssuanceLogModel(issue_id="ISS-009", date=date(2024,1,25), month=1, quarter=1, item_code="HK-027", qty=8,  uom="Kg",    rate=100, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff",      issued_by="Store Keeper", remarks="Garbage bags"),
        models.IssuanceLogModel(issue_id="ISS-010", date=date(2024,1,28), month=1, quarter=1, item_code="EL-049", qty=5,  uom="Piece", rate=180, location_code="STORE-CH", department="Maintenance",  issued_to="Electrician",   issued_by="Store Keeper", remarks="MCB replacement"),
        models.IssuanceLogModel(issue_id="ISS-011", date=date(2024,2,5),  month=2, quarter=1, item_code="HK-036", qty=10, uom="Kg",    rate=46,  location_code="CH-1B",    department="Admin",        issued_to="Pantry Staff",  issued_by="Admin",        remarks="Sugar stock"),
        models.IssuanceLogModel(issue_id="ISS-012", date=date(2024,2,10), month=2, quarter=1, item_code="HK-041", qty=5,  uom="Pair",  rate=85,  location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff",      issued_by="Store Keeper", remarks="Gloves for team"),
        # Mar–Dec: realistic monthly HK spend across all locations
        models.IssuanceLogModel(issue_id="ISS-013", date=date(2024,3,5),  month=3,  quarter=1, item_code="HK-001", qty=25, uom="Liter", rate=310, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Floor cleaner Mar"),
        models.IssuanceLogModel(issue_id="ISS-014", date=date(2024,3,12), month=3,  quarter=1, item_code="HK-010", qty=120,uom="Roll",  rate=14,  location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet paper Mar"),
        models.IssuanceLogModel(issue_id="ISS-015", date=date(2024,3,18), month=3,  quarter=1, item_code="HK-009", qty=8,  uom="Liter", rate=380, location_code="CH-2B",    department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Hand wash Mar"),
        models.IssuanceLogModel(issue_id="ISS-016", date=date(2024,3,22), month=3,  quarter=1, item_code="EL-019", qty=12, uom="Piece", rate=95,  location_code="STORE-CH", department="Maintenance",  issued_to="Electrician", issued_by="Store Keeper", remarks="Bulbs Mar"),
        models.IssuanceLogModel(issue_id="ISS-017", date=date(2024,4,4),  month=4,  quarter=2, item_code="HK-004", qty=18, uom="Liter", rate=300, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet cleaner Apr"),
        models.IssuanceLogModel(issue_id="ISS-018", date=date(2024,4,15), month=4,  quarter=2, item_code="HK-033", qty=5,  uom="Kg",    rate=560, location_code="MS",       department="Admin",        issued_to="Pantry Staff", issued_by="Admin", remarks="Tea Apr"),
        models.IssuanceLogModel(issue_id="ISS-019", date=date(2024,4,22), month=4,  quarter=2, item_code="HK-027", qty=12, uom="Kg",    rate=100, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Garbage bags Apr"),
        models.IssuanceLogModel(issue_id="ISS-020", date=date(2024,5,6),  month=5,  quarter=2, item_code="HK-001", qty=28, uom="Liter", rate=310, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Floor cleaner May"),
        models.IssuanceLogModel(issue_id="ISS-021", date=date(2024,5,14), month=5,  quarter=2, item_code="HK-010", qty=130,uom="Roll",  rate=14,  location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet paper May"),
        models.IssuanceLogModel(issue_id="ISS-022", date=date(2024,5,20), month=5,  quarter=2, item_code="EL-023", qty=10, uom="Piece", rate=265, location_code="CH-1B",    department="Maintenance",  issued_to="Electrician", issued_by="Store Keeper", remarks="Tube lights May"),
        models.IssuanceLogModel(issue_id="ISS-023", date=date(2024,6,3),  month=6,  quarter=2, item_code="HK-009", qty=10, uom="Liter", rate=380, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Hand wash Jun"),
        models.IssuanceLogModel(issue_id="ISS-024", date=date(2024,6,12), month=6,  quarter=2, item_code="HK-004", qty=20, uom="Liter", rate=300, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet cleaner Jun"),
        models.IssuanceLogModel(issue_id="ISS-025", date=date(2024,6,25), month=6,  quarter=2, item_code="HK-036", qty=12, uom="Kg",    rate=46,  location_code="STORE-CH", department="Admin",        issued_to="Pantry Staff", issued_by="Admin", remarks="Sugar Jun"),
        models.IssuanceLogModel(issue_id="ISS-026", date=date(2024,7,5),  month=7,  quarter=3, item_code="HK-001", qty=30, uom="Liter", rate=310, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Floor cleaner Jul"),
        models.IssuanceLogModel(issue_id="ISS-027", date=date(2024,7,14), month=7,  quarter=3, item_code="HK-010", qty=140,uom="Roll",  rate=14,  location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet paper Jul"),
        models.IssuanceLogModel(issue_id="ISS-028", date=date(2024,7,22), month=7,  quarter=3, item_code="EL-019", qty=14, uom="Piece", rate=95,  location_code="STORE-CH", department="Maintenance",  issued_to="Electrician", issued_by="Store Keeper", remarks="Bulbs Jul"),
        models.IssuanceLogModel(issue_id="ISS-029", date=date(2024,8,6),  month=8,  quarter=3, item_code="HK-009", qty=12, uom="Liter", rate=380, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Hand wash Aug"),
        models.IssuanceLogModel(issue_id="ISS-030", date=date(2024,8,15), month=8,  quarter=3, item_code="HK-004", qty=22, uom="Liter", rate=300, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet cleaner Aug"),
        models.IssuanceLogModel(issue_id="ISS-031", date=date(2024,8,25), month=8,  quarter=3, item_code="HK-033", qty=6,  uom="Kg",    rate=560, location_code="CH-1B",    department="Admin",        issued_to="Pantry Staff", issued_by="Admin", remarks="Tea Aug"),
        models.IssuanceLogModel(issue_id="ISS-032", date=date(2024,9,4),  month=9,  quarter=3, item_code="HK-001", qty=26, uom="Liter", rate=310, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Floor cleaner Sep"),
        models.IssuanceLogModel(issue_id="ISS-033", date=date(2024,9,13), month=9,  quarter=3, item_code="HK-027", qty=14, uom="Kg",    rate=100, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Garbage bags Sep"),
        models.IssuanceLogModel(issue_id="ISS-034", date=date(2024,9,22), month=9,  quarter=3, item_code="EL-023", qty=8,  uom="Piece", rate=265, location_code="MS",       department="Maintenance",  issued_to="Electrician", issued_by="Store Keeper", remarks="Tube lights Sep"),
        models.IssuanceLogModel(issue_id="ISS-035", date=date(2024,10,7), month=10, quarter=4, item_code="HK-009", qty=11, uom="Liter", rate=380, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Hand wash Oct"),
        models.IssuanceLogModel(issue_id="ISS-036", date=date(2024,10,16),month=10, quarter=4, item_code="HK-010", qty=150,uom="Roll",  rate=14,  location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet paper Oct"),
        models.IssuanceLogModel(issue_id="ISS-037", date=date(2024,10,24),month=10, quarter=4, item_code="HK-004", qty=24, uom="Liter", rate=300, location_code="CH-2B",    department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet cleaner Oct"),
        models.IssuanceLogModel(issue_id="ISS-038", date=date(2024,11,5), month=11, quarter=4, item_code="HK-001", qty=32, uom="Liter", rate=310, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Floor cleaner Nov"),
        models.IssuanceLogModel(issue_id="ISS-039", date=date(2024,11,14),month=11, quarter=4, item_code="HK-033", qty=7,  uom="Kg",    rate=560, location_code="STORE-CH", department="Admin",        issued_to="Pantry Staff", issued_by="Admin", remarks="Tea Nov"),
        models.IssuanceLogModel(issue_id="ISS-040", date=date(2024,11,22),month=11, quarter=4, item_code="EL-019", qty=18, uom="Piece", rate=95,  location_code="MS",       department="Maintenance",  issued_to="Electrician", issued_by="Store Keeper", remarks="Bulbs Nov"),
        models.IssuanceLogModel(issue_id="ISS-041", date=date(2024,12,4), month=12, quarter=4, item_code="HK-009", qty=14, uom="Liter", rate=380, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Hand wash Dec"),
        models.IssuanceLogModel(issue_id="ISS-042", date=date(2024,12,12),month=12, quarter=4, item_code="HK-004", qty=26, uom="Liter", rate=300, location_code="MS",       department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Toilet cleaner Dec"),
        models.IssuanceLogModel(issue_id="ISS-043", date=date(2024,12,20),month=12, quarter=4, item_code="HK-027", qty=16, uom="Kg",    rate=100, location_code="STORE-CH", department="Housekeeping", issued_to="HK Staff", issued_by="Store Keeper", remarks="Garbage bags Dec"),
        models.IssuanceLogModel(issue_id="ISS-044", date=date(2024,12,28),month=12, quarter=4, item_code="HK-036", qty=15, uom="Kg",    rate=46,  location_code="CH-1B",    department="Admin",        issued_to="Pantry Staff", issued_by="Admin", remarks="Sugar year-end stock"),
    ]
    db.add_all(issuances); db.commit()
    print(f"  OK: 16 inventory | 7 PRs | 5 POs | 4 GRNs | 44 issuances (all 12 months)")


    print("Seeding returns log...")
    returns = [
        models.ReturnLogModel(return_id="RET-001", return_date=date(2024,1,15), grn_ref="GRN-2024-002", item_code="EL-019", item_name="LED Bulb 9W B22", qty_returned=2, uom="Piece", vendor_code="VND-008", reason="Damaged in transit", status="Credit Received", credit_note="CN-V8-001", remarks="2 bulbs had cracked glass. Credit note received within 7 days."),
    ]
    db.add_all(returns); db.commit()
    print(f"  OK: {len(returns)} returns")

    print("Seeding consumption norms (full Excel data)...")
    norms_full = [
        models.ConsumptionNormModel(item_code="HK-001", item_name="Floor Cleaner Regular 5L",   category="Cleaning Chemicals", basis="Per 1000 SqFt", norm_value=0.5,  norm_unit="Liter", rate=310, cost_per_unit=155.0,  frequency="Monthly", remarks="500ml diluted cleans 1000 sqft weekly; 4 weeks = 2L per 1000 sqft; concentrated = 0.5L"),
        models.ConsumptionNormModel(item_code="HK-003", item_name="Glass Cleaner 5L",            category="Cleaning Chemicals", basis="Per 1000 SqFt", norm_value=0.15, norm_unit="Liter", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="150ml per 1000 sqft of glass area per month"),
        models.ConsumptionNormModel(item_code="HK-004", item_name="Toilet Cleaner Liquid 5L",    category="Cleaning Chemicals", basis="Per Washroom",  norm_value=2.0,  norm_unit="Liter", rate=300, cost_per_unit=600.0,  frequency="Monthly", remarks="500ml per WC per week x 4 WCs avg = 2L per washroom"),
        models.ConsumptionNormModel(item_code="HK-005", item_name="Surface Disinfectant 5L",     category="Cleaning Chemicals", basis="Per 1000 SqFt", norm_value=0.3,  norm_unit="Liter", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="High-touch surfaces cleaned daily"),
        models.ConsumptionNormModel(item_code="HK-007", item_name="Phenyl White 5L",             category="Cleaning Chemicals", basis="Per 1000 SqFt", norm_value=0.4,  norm_unit="Liter", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="Common areas, stairs, lobbies"),
        models.ConsumptionNormModel(item_code="HK-009", item_name="Hand Wash Liquid 5L",         category="Washroom Supplies",  basis="Per Person",    norm_value=0.15, norm_unit="Liter", rate=380, cost_per_unit=57.0,   frequency="Monthly", remarks="~5ml per wash x 30 washes/person/month = 150ml"),
        models.ConsumptionNormModel(item_code="HK-010", item_name="Toilet Paper Roll Regular",   category="Washroom Supplies",  basis="Per Person",    norm_value=4.0,  norm_unit="Roll",  rate=14,  cost_per_unit=56.0,   frequency="Monthly", remarks="1 roll per person per week"),
        models.ConsumptionNormModel(item_code="HK-012", item_name="Paper Towel C-Fold",          category="Washroom Supplies",  basis="Per Person",    norm_value=2.0,  norm_unit="Pack",  rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="~3 sheets per wash x 30 washes = 90 sheets; buffer = 2 packs"),
        models.ConsumptionNormModel(item_code="HK-014", item_name="Air Freshener Spray",         category="Washroom Supplies",  basis="Per Washroom",  norm_value=2.0,  norm_unit="Can",   rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="1 can per washroom per 15 days"),
        models.ConsumptionNormModel(item_code="HK-015", item_name="Urinal Screen Deodorizing",   category="Washroom Supplies",  basis="Per Urinal",    norm_value=1.0,  norm_unit="Piece", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="Replace every 30 days"),
        models.ConsumptionNormModel(item_code="HK-017", item_name="Mop Cotton 400g",             category="Cleaning Tools",     basis="Per 1000 SqFt", norm_value=0.17, norm_unit="Piece", rate=95,  cost_per_unit=16.15,  frequency="Monthly", remarks="1 mop per 2000 sqft replaced quarterly; monthly = 0.17"),
        models.ConsumptionNormModel(item_code="HK-023", item_name="Scrub Pad Green Heavy Duty",  category="Cleaning Tools",     basis="Per Washroom",  norm_value=4.0,  norm_unit="Piece", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="1 pad per week per washroom"),
        models.ConsumptionNormModel(item_code="HK-024", item_name="Cleaning Cloth Microfiber",   category="Cleaning Tools",     basis="Per 1000 SqFt", norm_value=2.0,  norm_unit="Piece", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="2 cloths per 1000 sqft replaced monthly"),
        models.ConsumptionNormModel(item_code="HK-027", item_name="Garbage Bag Small 17x19",     category="Waste Management",   basis="Per Person",    norm_value=0.3,  norm_unit="Kg",    rate=100, cost_per_unit=30.0,   frequency="Monthly", remarks="1 bag/day = 30 bags/person/month; ~100 bags/kg = 0.3 kg"),
        models.ConsumptionNormModel(item_code="HK-028", item_name="Garbage Bag Medium 19x21",    category="Waste Management",   basis="Per Washroom",  norm_value=1.0,  norm_unit="Kg",    rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="2 bags/day per washroom = 60 bags; ~60 bags/kg = 1 kg"),
        models.ConsumptionNormModel(item_code="HK-029", item_name="Garbage Bag Large 24x30",     category="Waste Management",   basis="Per 1000 SqFt", norm_value=0.5,  norm_unit="Kg",    rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="Common area bins, 1 bag/day per 2000 sqft"),
        models.ConsumptionNormModel(item_code="HK-033", item_name="Tea Premium (Wagh Bakri)",    category="Pantry",             basis="Per Person",    norm_value=0.1,  norm_unit="Kg",    rate=560, cost_per_unit=56.0,   frequency="Monthly", remarks="~3g per cup x 3 cups/day x 22 days = 200g; accounting for visitors = 100g"),
        models.ConsumptionNormModel(item_code="HK-036", item_name="Sugar White",                 category="Pantry",             basis="Per Person",    norm_value=0.3,  norm_unit="Kg",    rate=46,  cost_per_unit=13.8,   frequency="Monthly", remarks="~10g per cup x 3 cups x 22 days = 660g; shared usage = 300g"),
        models.ConsumptionNormModel(item_code="HK-037", item_name="Milk Tetra Pack 1L",          category="Pantry",             basis="Per Person",    norm_value=1.5,  norm_unit="Liter", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="~50ml per cup x 3 cups x 22 days = 3.3L; shared = 1.5L"),
        models.ConsumptionNormModel(item_code="HK-038", item_name="Paper Cup 150ml",             category="Pantry",             basis="Per Person",    norm_value=60.0, norm_unit="Piece", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="~2-3 cups/day x 22 days = 55-66 cups"),
        models.ConsumptionNormModel(item_code="HK-039", item_name="Water Jar 20L Refill",        category="Pantry",             basis="Per Person",    norm_value=0.8,  norm_unit="Jar",   rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="~2L water/person/day x 22 days = 44L = 2.2 jars; shared = 0.8"),
        models.ConsumptionNormModel(item_code="EL-019", item_name="LED Bulb 9W B22",             category="Electrical",         basis="Per 1000 SqFt", norm_value=0.2,  norm_unit="Piece", rate=95,  cost_per_unit=19.0,   frequency="Monthly", remarks="~10% replacement rate annually = 1.2/year = 0.1/month; buffer = 0.2"),
        models.ConsumptionNormModel(item_code="EL-023", item_name="LED Tube Light 20W 4ft",      category="Electrical",         basis="Per 1000 SqFt", norm_value=0.15, norm_unit="Piece", rate=265, cost_per_unit=39.75,  frequency="Monthly", remarks="~8% replacement rate annually"),
        models.ConsumptionNormModel(item_code="HK-041", item_name="Gloves Rubber Household",     category="PPE & Safety",       basis="Per Washroom",  norm_value=1.0,  norm_unit="Pair",  rate=85,  cost_per_unit=85.0,   frequency="Monthly", remarks="1 pair per washroom per month for HK staff"),
        models.ConsumptionNormModel(item_code="HK-044", item_name="Face Mask Surgical 3-ply",    category="PPE & Safety",       basis="Per Washroom",  norm_value=15.0, norm_unit="Piece", rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="1 mask/day for HK staff per washroom area; 15 working days avg"),
        models.ConsumptionNormModel(item_code="HK-047", item_name="Cockroach Killer Spray",      category="Pest Control",       basis="Per 1000 SqFt", norm_value=0.3,  norm_unit="Can",   rate=0,   cost_per_unit=0,      frequency="Monthly", remarks="Spot treatment as needed"),
    ]
    # Only seed if table is empty
    existing = db.query(models.ConsumptionNormModel).count()
    if existing < 5:
        db.add_all(norms_full); db.commit()
        print(f"  OK: {len(norms_full)} consumption norms")
    else:
        print(f"  OK: {existing} norms already exist")

    # ── THIRD-PARTY SERVICES ──────────────────────────────────────────────────
    print("Seeding third-party services...")
    if 'third_party_services' not in models.Base.metadata.tables:
        models.Base.metadata.create_all(engine)
    # drop & recreate to avoid duplicates on re-run
    from sqlalchemy import text
    db.execute(text("DELETE FROM third_party_services"))
    db.commit()
    services = [
        models.ThirdPartyServiceModel(location_code="MS",    service_type="Deep Cleaning",  vendor_name="CleanPro Services",   vendor_contact="9876500001", monthly_cost=8500, scope="Weekly deep cleaning of all washrooms, pantry, meeting rooms. Monthly carpet shampooing.", status="Active"),
        models.ThirdPartyServiceModel(location_code="CH-1B", service_type="Pest Control",   vendor_name="PestAway India",       vendor_contact="9876500002", monthly_cost=2200, scope="Monthly pest control. Quarterly rodent treatment.", status="Active"),
        models.ThirdPartyServiceModel(location_code="BRD",   service_type="Daily Cleaning", vendor_name="Shree Cleaning Co.",   vendor_contact="9876500003", monthly_cost=6000, scope="Daily housekeeping - mopping, dusting, washroom maintenance.", status="Active"),
    ]
    db.add_all(services); db.commit()
    print(f"  OK: {len(services)} third-party services")

    # ── RETURNS LOG ───────────────────────────────────────────────────────────
    print("Seeding returns log...")
    if 'returns_log' not in models.Base.metadata.tables:
        models.Base.metadata.create_all(engine)
    db.execute(text("DELETE FROM returns_log"))
    db.commit()
    returns = [
        models.ReturnLogModel(return_id="RET-001", return_date=date(2024,1,15), grn_ref="GRN-2024-002", item_code="EL-019", item_name="LED Bulb 9W B22", qty_returned=2, uom="Piece", vendor_code="VND-008", reason="Damaged in transit", status="Credit Received", credit_note="CN-V8-001", remarks="2 bulbs had cracked glass. Credit note received within 7 days."),
    ]
    db.add_all(returns); db.commit()
    print(f"  OK: {len(returns)} return records")

    print("\n" + "="*55)
    print("  ALL DATA SEEDED SUCCESSFULLY!")
    print("  Locations:           10")
    print("  Vendors:             10")
    print("  HK Master Items:    128")
    print("  Active Items:        16")
    print("  Consumption Norms:   26")
    print("  3rd Party Services:   3")
    print("  Inventory:           16")
    print("  PRs / POs / GRNs:  7/5/4")
    print("  Issuances:           12")
    print("  Returns:              1")
    print("="*55)

except Exception as e:
    print(f"\nERROR: {e}")
    import traceback; traceback.print_exc()
    db.rollback()
finally:
    db.close()